### ISSUE TITLE
`to_input_rlp/1` should guard against invalid attributes

### ISSUE THREAD

**Issue by achiurizo** [omisego/ex_plasma#29]
If `Utxo.to_input_rlp/1` or `Utxo.pos/1` are given attributes exceeding the maximum, the functions will still generate a utxo position with said values. This can create situations where it will no longer re-produce the same struct:

```elixir
iex(6)> utxo = %ExPlasma.Utxo{blknum: 1, txindex: 1_000_000_000, oindex: 0}
%ExPlasma.Utxo{
  amount: nil,
  blknum: 1,
  currency: nil,
  oindex: 0,
  output_type: 1,
  owner: nil,
  txindex: 1000000000 # :|
}
iex(7)> pos = ExPlasma.Utxo.pos(utxo)
10001000000000
iex(8)> ExPlasma.Utxo.new(pos)
{:ok,
 %ExPlasma.Utxo{
   amount: nil,
   blknum: 10001,  # :(
   currency: nil,
   oindex: 0,
   output_type: 1,
   owner: nil,
   txindex: 0
 }}
```

These functions should also run through the validation and return us an appropriate ok or error tuple.

**Comment by mederic-p** [comment]
Can we close this?
