### ISSUE TITLE
Add synchronous version of ExPlasma.Client calls

### ISSUE THREAD

**Issue by pgebal** [omisego/ex_plasma#36]
After making a deposit it would be nice to know it's mined on Ethereum and to know it's blknum. Using `ExPlasma` to do that is cumbersome.
Currently in `omg-load-testing` we handle it this way:   https://github.com/omisego/omg-load-testing/blob/1f1f34b6dee6b8c94256bb1f488dfe05fd487f77/lib/omg_perf/extended_perftest.ex#L86
(and it's not the best way as it assumes there is just one deposit from a given address in Ethereum block, but it's sufficient for our needs).
Could you add functions to synchronously make deposits and submit blocks? Preferably return value contains at least blknum.

**Comment by achiurizo** [comment]
Closing this as we are moving away from this library having the client calls. Will be porting that over to another library set.
